service: sls-golang-net
package:
  artifact: handler.zip
provider:
  name: aws
  runtime: python2.7
  stage: ${env:ENV}
  region: ${env:AWS_DEFAULT_REGION}
  profile: ${env:AWS_PROFILE}
functions:
  crud:
    handler: handler.Handler
    events:
      - http:
          path: todos
          method: post
          cors: true
      - http:
          path: todos
          method: get
          cors: true
      - http:
          path: todos/{id}
          method: get
          cors: true
      - http:
          path: todos/{id}
          method: put
          cors: true
      - http:
          path: todos/{id}
          method: delete
          cors: true