service: sls-golang-graphql
package:
  artifact: package.zip
provider:
  name: aws
  runtime: python2.7
  stage: ${env:ENV}
  region: ${env:AWS_REGION}
functions:
  graphql:
    handler: handler.Handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
